apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-perf-exec1
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: swr.cn-north-4.myhuaweicloud.com/cloud-course-2023112557/pyspark:3.4
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/work/perf_genre_topn.py
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  sparkConf:
    spark.hadoop.fs.s3a.endpoint: "obs.cn-north-4.myhuaweicloud.com"
    spark.hadoop.fs.s3a.path.style.access: "true"
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    env:
      - name: DATA_PATH
        value: "s3a://cloud-course-2023112557/douban_movies.csv"
  executor:
    cores: 1
    instances: 1
    memory: "1g"
