apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-to-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-to-redis
  template:
    metadata:
      labels:
        app: mqtt-to-redis
    spec:
      imagePullSecrets:
        - name: swr-secret
      containers:
        - name: bridge
          image: swr.cn-north-4.myhuaweicloud.com/cloud-course-2023112557/mqtt-to-redis:v1
          env:
            - name: MQTT_HOST
              value: mqtt-broker
            - name: MQTT_TOPIC
              value: edge/sensor/temperature
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
